#
# Module manifest for module 'LinuxLoveWindows'
#
# Generated by: Sidik Hadi Kurniadi
#
# Generated on: 5/19/2025
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule        = '.\LinuxLoveWindows.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.2'

    # Supported PSEditions
    CompatiblePSEditions = 'Core'

    # ID used to uniquely identify this module
    GUID              = 'b1e7e2e2-1234-4cde-9abc-123456789abc'

    # Author of this module
    Author            = 'Sidik Hadi Kurniadi'

    # Description of the functionality provided by this module
    Description       = 'LinuxLoveWindows is a PowerShell module designed to bridge the gap between Linux and Windows. It allows users to import Linux commands into their PowerShell sessions, enabling seamless interoperability between Windows Subsystem for Linux (WSL) and PowerShell. 🚀'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '6.0'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @('WslInterop')

    # Functions to export from this module
    FunctionsToExport = @('Initialize-Linux','Import-Linux')

    # Cmdlets to export from this module
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport   = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/cdhtlr/LinuxLoveWindows/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/cdhtlr/LinuxLoveWindows'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
